name: Node.js Package

on:
  push:
    tags:
      - '*.*'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Setup"
        uses: actions/setup-node@v2
      - name: "Create Release"
        uses: softprops/action-gh-release@78c309ef59fdb9557cd6574f2e0be552936ed728
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Configure npm"
        run: touch .npmrc && echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: "Publish"
        run: npm publish --access public